// <auto-generated />
using System;
using AuroraPet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Aurora.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AuroraDbContext))]
    [Migration("20260913211119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuroraPet.Payments.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("STRIPE_PRICE_ID");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIER");

                    b.HasKey("Id");

                    b.HasIndex("StripePriceId")
                        .IsUnique()
                        .HasDatabaseName("UX_PLAN_STRIPE_PRICE");

                    b.ToTable("TB_SUBSCRIPTION_PLAN", (string)null);
                });

            modelBuilder.Entity("AuroraPet.Payments.Domain.Entities.TutorSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CURRENT_PERIOD_END");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("FIREBASE_UID");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PLAN_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("STRIPE_CUSTOMER_ID");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("STRIPE_SUBSCRIPTION_ID");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .HasDatabaseName("IX_SUBSCRIPTION_FIREBASE_UID");

                    b.HasIndex("PlanId");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("UX_SUBSCRIPTION_STRIPE_ID");

                    b.ToTable("TB_TUTOR_SUBSCRIPTION", (string)null);
                });

            modelBuilder.Entity("AuroraPet.Payments.Domain.Entities.TutorSubscription", b =>
                {
                    b.HasOne("AuroraPet.Payments.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SUBSCRIPTION_PLAN");
                });
#pragma warning restore 612, 618
        }
    }
}
